backend:
  name: github
  repo: DomtronVox/CFF-testsite # Path to your Github repository
  branch: master # Branch to update

media_folder: src/files/images/
public_folder: images/

collections: # A list of collections the CMS should be able to edit
  - label: "Site Settings"
    name: "site_config"
    files:
      - label: "General Settings"
        name: "general_config"
        file: "src/documents/config/site.json"
        fields:
          - {label: "'Brand' (e.g. Company Inc.)", name: "brand", widget: "string"}
          - {label: "Title", name: "title", widget: "string", hint: "Is added to page header as large text."}
          - {label: "Subtitle", name: "subtitle", widget: "string", hint: "Is added to page headers as small text."}
          - {label: "Site Description", name: "description", widget: "string", hint: "Is used for search engine bots."}
          - {label: "URL (e.g. http://your-site.com/)", name: "url", widget: "string"}    
          - {label: "Favicon", name: "favicon_image", widget: "image", hint: "The icon that appears in the browser tabs."}
          - {label: "Logo", name: "logo_image", widget: "image", hint: "The image used as the logo."}
          - {label: "Name of Site Posts (Examples: 'Blog' or 'News')", name: "posts_name", widget: "string"}
          - {label: "Name of Extra Links sidebar (Examples: 'Our Friends' or 'Interesting Links')", name: "sidebar_links_name", widget: "string"}
          - label: "Sidebar Extra Links"
            name: "sidebar_links_list"
            widget: "list"
            hint: "Leave empty to remove the extra sidebar."
            fields:
                  - {label: "Link Text", name: "text", widget: "string"} 
                  - {label: "Link URL (i.e. relative like /about.html or absolute like http://coolsite.org/cool_things.html)", name: "link", widget: "string"} 
      - label: "Layout Settings"
        name: "layout_config"
        file: "src/documents/config/positioning.json"
        fields:
          - {label: "Menu Bar Location", name: "nav_position", widget: "select", default: "top", options: ["top", "in_header", "left", "right"] }
          - {label: "Sidebar Location", name: "aside_position", widget: "select", default: "right", options: ["right", "left", "off"] }
      - label: "Main Menu"
        name: "menu_config"
        file: "src/documents/config/menu.json"
        fields:
          - label: "Menu Pages and Order"
            name: "menu_config_list"
            widget: "list"
            fields:
              - {label: "Menu Text", name: "text", widget: "string"} 
              - {label: "Menu Link", name: "link", widget: "string", hint: "I.E. relative like /about.html or absolute like http://coolsite.org/cool_things.html."} 
              - label: "Sub-Menu Pages and Order"
                name: "submenu_config_list"
                widget: "list"
                fields:
                  - {label: "Sub-Menu Text", name: "text", widget: "string"} 
                  - {label: "Sub-Menu Link (i.e. relative like /about.html or absolute like http://coolsite.org/cool_things.html)", name: "link", widget: "string"}
              
  - name: "pages"
    label: "Pages"
    folder: "src/documents"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 

      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "Pages"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default.pug"}

      
  - name: "posts"
    label: "Posts"
    folder: "src/documents/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Summery of Post", name: "summery_text", widget: "text", hint: "Give an idea of the post's content when in a list of posts."}
      - {label: "Include Summery in Post Body", name: "put_summery_in_body", widget: "boolean", required:false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date (note not a scheduler, is just the date people see)", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"} 
      - label: "Tags"
        name: "tag_list"
        widget: "list"
        field: {label: "Tag", name: "tag", widget: "string", pattern: ["^[a-z0-9 &*^%$#@!.]+$", "Tags must be all lower case."]}

      #hidden fields are not editable by the user but still show up in the file's front matter
      - {label: "Collection", name: "collection", widget: "hidden", default: "posts"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post.pug"}

